rules:
  business:
    minAmount: 1000
    maxAmount: 20000
    minTerm: 30
    maxTerm: 365
  fraud-detection:
    amount-in-time-range:
      amount: ${rules.business.maxAmount}
      from: "00:00:00"
      to: "06:00:00"

cost:
  principalPercentage:
    percentage: 0.1


extension:
  term: 30