rules:
  business:
    maxAmount: 20000
    minTerm: 30
    maxTerm: 365
  fraud-detection:
    amount-in-time-range:
      amount: ${rules.business.maxAmount}
      from: "18:00:00"
      to: "19:00:00"


cost:
  principalPercentage:
    percentage: 10.0
